#!/bin/bash
set -e

command_string="spamassassin --lint"

# Copy rules to the right location

echo "ls -l"

echo ${GITHUB_WORKSPACE}
ls -l ${GITHUB_WORKSPACE}

find ${GITHUB_WORKSPACE} -name "*.cf" -exec cp {} /etc/spamassassin/ \;

echo "Command: $command_string"
eval "$command_string"
