#!/bin/bash
set -e

command_string="spamassassin --lint"

# Copy rules to the right location

echo ${WORKDIR}

find ${ACTION_DIRECTORY} -name "*.cf" -exec cp {} /etc/spamassassin/ \;

echo "Command: $command_string"
eval "$command_string"
