#!/bin/bash
set -e

command_string="spamassassin --lint"

# Copy rules to the right location

find . -name "*.cf" -exec cp {} /etc/spamassassin/ \;

echo "Command: $command_string"
eval "$command_string"
