---
name: Container CI

on:
  pull_request:
  schedule:
    - cron: '22 22 10 * *'

jobs:
  reusable-workflow:
    name: Reusable Workflow
    uses: hspaans/.github/.github/workflows/container-ci.yml@master
