---
name: Container CI

on:
  pull_request:
  push:
    branches:
      - master
      - v*
    tags:
      - v*
  schedule:
    - cron: '6 5 * * 1'

jobs:
  reusable-workflow:
    name: Reusable Workflow
    uses: hspaans/.github/.github/workflows/container-ci.yml@master
